### ISSUE TITLE
Panic with nil argument

### ISSUE THREAD

**Issue by Trial97** [cenkalti/rpc2#34]
Hi ,
I found the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x65d0a5]

goroutine 59 [running]:
testing.tRunner.func1.1(0x1bad020, 0x2ea23f0)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0000c8900)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x1bad020, 0x2ea23f0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cenkalti/rpc2/jsonrpc.(*jsonCodec).WriteRequest(0xc00043b4a0, 0xc00013e780, 0x0, 0x0, 0xc0008af388, 0x18)
	/go/pkg/mod/github.com/cenkalti/rpc2@v0.0.0-20210206021708-de76ddb08fa8/jsonrpc/jsonrpc.go:181 +0x85
github.com/cenkalti/rpc2.(*Client).send(0xc00013e770, 0xc00002e690)
	/go/pkg/mod/github.com/cenkalti/rpc2@v0.0.0-20210206021708-de76ddb08fa8/client.go:326 +0x1bf
github.com/cenkalti/rpc2.(*Client).Go(0xc00013e770, 0x1e6de70, 0x1c, 0x0, 0x0, 0x1a89540, 0xc0004c7a60, 0xc000700540, 0xc00002e640)
	/go/pkg/mod/github.com/cenkalti/rpc2@v0.0.0-20210206021708-de76ddb08fa8/client.go:265 +0xd0
github.com/cenkalti/rpc2.(*Client).Call(...)
	/go/pkg/mod/github.com/cenkalti/rpc2@v0.0.0-20210206021708-de76ddb08fa8/client.go:271
```
When calling a client with nil args like so:
```
client.Call("ping", nil,&reply)
```
This worked before this [PR](https://github.com/cenkalti/rpc2/pull/33) was merged.

Thanks,
Trial97

**Comment by cenkalti** [comment]
@Trial97 @edraac Can any of you send a PR for fix?

**Comment by edraac** [comment]
@cenkalti sure, I'll get on it asap.
